### PR TITLE
Precompute point multiplication results in pedersen

### PR DESCRIPTION
**Pull request by omerfirmak**
Provides 5x performance improvement

### CODE REVIEW

**Comment by omerfirmak** [comment]
@yelhousni, any chance we get an eye on this?

**Comment by omerfirmak** [comment]
> > @yelhousni, any chance we get an eye on this?
> 
> So the point is instead of computing `highPart*p2 + lowPart * p1` you precompute a table of multiples of `p1` and `p2` that you later lookup?

Yeah, pretty much.

16 values are precomputed for each nibble in highPart and lowPart. Then according to values of each nibble one of those values is selected per nibble and they are all summed up for the end result.

**Comment by yelhousni** [comment]
Right! I remember proposing something in these lines: https://github.com/ConsenSys/gnark-crypto/pull/327#issuecomment-1416053157

**Comment by omerfirmak** [comment]
Thanks! Anything I can help with to get this merged?

**Pull request merged**
