### PR TITLE
perf: sis tensor commitment

### PR DESCRIPTION
**Pull request by gbotrel**
see #252 #332 and #341 .

# Notes

cc @ThomasPiellard 

1. Modified the sage script to generate test cases, in particular `splitCoeffs` way of initializing the length of the result didn't work for other sis params.
2. The sage script now outputs a .json files that's parsed / tested through in .go.
3. Perf wise, we could save some memory allocs, but it doesn't seem to impact CPU that much so... skipping for now, we may be "fast enough" on `bn254`.

# Benchmarks

cc @AlexandreBelling 

```
goos: darwin
goarch: arm64
pkg: github.com/consensys/gnark-crypto/ecc/bn254/fr/sis
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=2/log2-degree=3-10         	     124	   9693181 ns/op	      9466 ns/field	     14986 ns/field(theory)	 1313072 B/op	   32785 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=2/log2-degree=3-10         	      61	  19088285 ns/op	      9321 ns/field	     14986 ns/field(theory)	 2625412 B/op	   65553 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=2/log2-degree=3-10         	      30	  38139276 ns/op	      9311 ns/field	     14986 ns/field(theory)	 5253360 B/op	  131087 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=2/log2-degree=3-10         	      14	  76548577 ns/op	      9344 ns/field	     14986 ns/field(theory)	10524949 B/op	  262159 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=2/log2-degree=3-10        	       7	 154377071 ns/op	      9423 ns/field	     14986 ns/field(theory)	21122652 B/op	  524295 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=2/log2-degree=3-10        	       4	 310006094 ns/op	      9461 ns/field	     14986 ns/field(theory)	42468336 B/op	 1048576 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=2/log2-degree=3-10        	       2	 612784916 ns/op	      9350 ns/field	     14986 ns/field(theory)	85983584 B/op	 2097141 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=4/log2-degree=4-10         	     208	   5721993 ns/op	      5588 ns/field	      9144 ns/field(theory)	  331355 B/op	    8210 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=4/log2-degree=4-10         	     100	  11616710 ns/op	      5672 ns/field	      9144 ns/field(theory)	  660030 B/op	   16402 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=4/log2-degree=4-10         	      50	  23005460 ns/op	      5616 ns/field	      9144 ns/field(theory)	 1319321 B/op	   32786 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=4/log2-degree=4-10         	      25	  45954860 ns/op	      5610 ns/field	      9144 ns/field(theory)	 2645769 B/op	   65554 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=4/log2-degree=4-10        	      12	  91640278 ns/op	      5593 ns/field	      9144 ns/field(theory)	 5333616 B/op	  131091 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=4/log2-degree=4-10        	       6	 185620208 ns/op	      5665 ns/field	      9144 ns/field(theory)	10838634 B/op	  262164 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=4/log2-degree=4-10        	       3	 366019917 ns/op	      5585 ns/field	      9144 ns/field(theory)	22372962 B/op	  524311 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=6/log2-degree=5-10         	     261	   4584861 ns/op	      4477 ns/field	      7196 ns/field(theory)	  115962 B/op	    2751 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=6/log2-degree=5-10         	     129	   9188792 ns/op	      4486 ns/field	      7196 ns/field(theory)	  225927 B/op	    5481 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=6/log2-degree=5-10         	      63	  18456245 ns/op	      4506 ns/field	      7196 ns/field(theory)	  447552 B/op	   10943 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=6/log2-degree=5-10         	      32	  37020508 ns/op	      4519 ns/field	      7196 ns/field(theory)	  896654 B/op	   21865 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=6/log2-degree=5-10        	      15	  74281869 ns/op	      4534 ns/field	      7196 ns/field(theory)	 1824013 B/op	   43711 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=6/log2-degree=5-10        	       7	 147355363 ns/op	      4497 ns/field	      7196 ns/field(theory)	 3801297 B/op	   87403 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=6/log2-degree=5-10        	       4	 295057406 ns/op	      4502 ns/field	      7196 ns/field(theory)	 8045556 B/op	  174787 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=10/log2-degree=6-10        	     361	   3306163 ns/op	      3228 ns/field	      4978 ns/field(theory)	   45557 B/op	     840 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=10/log2-degree=6-10        	     180	   6870231 ns/op	      3354 ns/field	      4978 ns/field(theory)	   78903 B/op	    1660 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=10/log2-degree=6-10        	      86	  13302157 ns/op	      3247 ns/field	      4978 ns/field(theory)	  146743 B/op	    3298 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=10/log2-degree=6-10        	      44	  26613098 ns/op	      3248 ns/field	      4978 ns/field(theory)	  286650 B/op	    6574 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=10/log2-degree=6-10       	      21	  53315161 ns/op	      3254 ns/field	      4978 ns/field(theory)	  586825 B/op	   13128 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=10/log2-degree=6-10       	      10	 106474850 ns/op	      3249 ns/field	      4978 ns/field(theory)	 1270924 B/op	   26237 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=10/log2-degree=6-10       	       5	 214645058 ns/op	      3275 ns/field	      4978 ns/field(theory)	 2948625 B/op	   52453 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=16/log2-degree=7-10        	     475	   2577987 ns/op	      2517 ns/field	      3524 ns/field(theory)	   35241 B/op	     277 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=16/log2-degree=7-10        	     226	   5248128 ns/op	      2562 ns/field	      3524 ns/field(theory)	   45923 B/op	     533 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=16/log2-degree=7-10        	     100	  10087598 ns/op	      2462 ns/field	      3524 ns/field(theory)	   68444 B/op	    1045 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=16/log2-degree=7-10        	      58	  20138146 ns/op	      2458 ns/field	      3524 ns/field(theory)	  115822 B/op	    2069 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=16/log2-degree=7-10       	      28	  40313403 ns/op	      2460 ns/field	      3524 ns/field(theory)	  226150 B/op	    4117 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=16/log2-degree=7-10       	      14	  80525524 ns/op	      2457 ns/field	      3524 ns/field(theory)	  502336 B/op	    8214 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=16/log2-degree=7-10       	       7	 160487548 ns/op	      2449 ns/field	      3524 ns/field(theory)	 1279402 B/op	   16407 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=32/log2-degree=8-10        	     714	   1674274 ns/op	      1635 ns/field	      1968 ns/field(theory)	   52095 B/op	      87 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=32/log2-degree=8-10        	     358	   3320193 ns/op	      1621 ns/field	      1968 ns/field(theory)	   54930 B/op	     151 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=32/log2-degree=8-10        	     181	   6594958 ns/op	      1610 ns/field	      1968 ns/field(theory)	   61132 B/op	     279 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=32/log2-degree=8-10        	      90	  13170102 ns/op	      1607 ns/field	      1968 ns/field(theory)	   75748 B/op	     535 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=32/log2-degree=8-10       	      44	  26322546 ns/op	      1606 ns/field	      1968 ns/field(theory)	  114233 B/op	    1047 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=32/log2-degree=8-10       	      21	  52771726 ns/op	      1610 ns/field	      1968 ns/field(theory)	  231225 B/op	    2071 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=32/log2-degree=8-10       	      10	 105282317 ns/op	      1606 ns/field	      1968 ns/field(theory)	  632708 B/op	    4120 allocs/op
PASS
ok  	github.com/consensys/gnark-crypto/ecc/bn254/fr/sis	74.703s

```

### CODE REVIEW

**Comment by gbotrel** [comment]
@ThomasPiellard on this branch it seems you added this:
```
NewDomain(m uint64, shift ...fr.Element)
```
for the fft.

Also you mentioned an idea to store less things for the `Twiddles` ?

**Comment by ThomasPiellard** [comment]
Yes for the twiddles you can only store the list` [w^i | i=0..n-1 ]` where n=cardinality fft and at each stage instead of accessing `twiddles[stage][k]` you would access `twiddles[ (1<<stage)*k ]`. But when I tested it it's not faster...

**Comment by gbotrel** [comment]
without algorithmic change, just single threaded FFT and few less memallocs:

```
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10            393748778     86143388      -78.12%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10            298292219     95346125      -68.04%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10            338960125     150031625     -55.74%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10           409702083     213407383     -47.91%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10      386613875     85604388      -77.86%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10      295146490     95329128      -67.70%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10      348827889     149104625     -57.26%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10     406781764     212140017     -47.85%

benchmark                                                                         old allocs     new allocs     delta
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10            1430552        260108         -81.82%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10            975386         130061         -86.67%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10            823659         86712          -89.47%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10           1014442        52033          -94.87%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10      1430554        260108         -81.82%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10      975385         130061         -86.67%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10      823658         86712          -89.47%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10     1014447        52033          -94.87%

benchmark                                                                         old bytes     new bytes     delta
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10            129321381     45827176      -64.56%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10            119180376     42707048      -64.17%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10            145362605     56236790      -61.31%
BenchmarkSISRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10           186916162     72056889      -61.45%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=2-log-2-degree=3-10      129322381     45827175      -64.56%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=4-log-2-degree=4-10      119180344     42707048      -64.17%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=6-log-2-degree=5-10      145362594     56236790      -61.31%
BenchmarkSISSparseRef/ring-sis/nb-input=1024-log-2-bound=10-log-2-degree=6-10     186916674     72056889      -61.45%
```

**Comment by gbotrel** [comment]
```
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=2/log2-degree=3-10                      120           9955875 ns/op              9722 ns/field          14986 ns/field(theory)      1312020 B/op      32776 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=2/log2-degree=3-10                       60          19578033 ns/op              9560 ns/field          14986 ns/field(theory)      2622740 B/op      65544 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=2/log2-degree=3-10                       28          39127616 ns/op              9553 ns/field          14986 ns/field(theory)      5244180 B/op     131080 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=2/log2-degree=3-10                       14          78560988 ns/op              9590 ns/field          14986 ns/field(theory)     10486981 B/op     262150 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=2/log2-degree=3-10                       7         157000637 ns/op              9583 ns/field          14986 ns/field(theory)     20972582 B/op     524290 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=2/log2-degree=3-10                       4         312633323 ns/op              9541 ns/field          14986 ns/field(theory)     41943780 B/op    1048570 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=2/log2-degree=3-10                       2         626305708 ns/op              9557 ns/field          14986 ns/field(theory)     83886024 B/op    2097126 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=4/log2-degree=4-10                      201           5903307 ns/op              5765 ns/field           9144 ns/field(theory)       330340 B/op       8203 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=4/log2-degree=4-10                      100          11787955 ns/op              5756 ns/field           9144 ns/field(theory)       658020 B/op      16395 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=4/log2-degree=4-10                       49          23640935 ns/op              5772 ns/field           9144 ns/field(theory)      1313380 B/op      32779 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=4/log2-degree=4-10                       25          47585487 ns/op              5809 ns/field           9144 ns/field(theory)      2624100 B/op      65547 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=4/log2-degree=4-10                      12          94537066 ns/op              5770 ns/field           9144 ns/field(theory)      5245541 B/op     131083 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=4/log2-degree=4-10                       6         190084375 ns/op              5801 ns/field           9144 ns/field(theory)     10488421 B/op     262155 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=4/log2-degree=4-10                       3         378568264 ns/op              5776 ns/field           9144 ns/field(theory)     20974186 B/op     524299 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=6/log2-degree=5-10                      252           4741482 ns/op              4630 ns/field           7196 ns/field(theory)       114500 B/op       2744 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=6/log2-degree=5-10                      126           9482334 ns/op              4630 ns/field           7196 ns/field(theory)       223700 B/op       5474 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=6/log2-degree=5-10                       62          18989799 ns/op              4636 ns/field           7196 ns/field(theory)       442180 B/op      10936 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=6/log2-degree=5-10                       31          37999391 ns/op              4638 ns/field           7196 ns/field(theory)       879060 B/op      21858 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=6/log2-degree=5-10                      15          76203411 ns/op              4651 ns/field           7196 ns/field(theory)      1752900 B/op      43704 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=6/log2-degree=5-10                       7         152917458 ns/op              4666 ns/field           7196 ns/field(theory)      3500500 B/op      87394 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=6/log2-degree=5-10                       4         304787302 ns/op              4650 ns/field           7196 ns/field(theory)      6995780 B/op     174776 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=10/log2-degree=6-10                     349           3425358 ns/op              3345 ns/field           4978 ns/field(theory)        43140 B/op        833 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=10/log2-degree=6-10                     174           6880503 ns/op              3359 ns/field           4978 ns/field(theory)        75940 B/op       1653 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=10/log2-degree=6-10                      85          13742337 ns/op              3355 ns/field           4978 ns/field(theory)       141460 B/op       3291 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=10/log2-degree=6-10                      43          27463756 ns/op              3352 ns/field           4978 ns/field(theory)       272500 B/op       6567 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=10/log2-degree=6-10                     21          55117698 ns/op              3364 ns/field           4978 ns/field(theory)       534660 B/op      13121 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=10/log2-degree=6-10                     10         110227021 ns/op              3364 ns/field           4978 ns/field(theory)      1058980 B/op      26229 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=10/log2-degree=6-10                      5         219912867 ns/op              3355 ns/field           4978 ns/field(theory)      2107542 B/op      52443 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=16/log2-degree=7-10                     460           2595578 ns/op              2534 ns/field           3524 ns/field(theory)        30820 B/op        270 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=16/log2-degree=7-10                     230           5186202 ns/op              2532 ns/field           3524 ns/field(theory)        41060 B/op        526 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=16/log2-degree=7-10                     100          10387156 ns/op              2536 ns/field           3524 ns/field(theory)        61540 B/op       1038 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=16/log2-degree=7-10                      56          20754748 ns/op              2533 ns/field           3524 ns/field(theory)       102500 B/op       2062 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=16/log2-degree=7-10                     27          41576835 ns/op              2537 ns/field           3524 ns/field(theory)       184420 B/op       4110 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=16/log2-degree=7-10                     14          83201560 ns/op              2539 ns/field           3524 ns/field(theory)       348260 B/op       8206 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=16/log2-degree=7-10                      7         166186000 ns/op              2535 ns/field           3524 ns/field(theory)       675940 B/op      16398 allocs/op
BenchmarkSIS/ring-sis/inputs=1024/log2-bound=32/log2-degree=8-10                     697           1712981 ns/op              1672 ns/field           1968 ns/field(theory)        43624 B/op         80 allocs/op
BenchmarkSIS/ring-sis/inputs=2048/log2-bound=32/log2-degree=8-10                     350           3400128 ns/op              1660 ns/field           1968 ns/field(theory)        46184 B/op        144 allocs/op
BenchmarkSIS/ring-sis/inputs=4096/log2-bound=32/log2-degree=8-10                     176           6792244 ns/op              1658 ns/field           1968 ns/field(theory)        51304 B/op        272 allocs/op
BenchmarkSIS/ring-sis/inputs=8192/log2-bound=32/log2-degree=8-10                      86          13541054 ns/op              1653 ns/field           1968 ns/field(theory)        61544 B/op        528 allocs/op
BenchmarkSIS/ring-sis/inputs=16384/log2-bound=32/log2-degree=8-10                     43          27080639 ns/op              1652 ns/field           1968 ns/field(theory)        82024 B/op       1040 allocs/op
BenchmarkSIS/ring-sis/inputs=32768/log2-bound=32/log2-degree=8-10                     21          54090532 ns/op              1650 ns/field           1968 ns/field(theory)       122984 B/op       2064 allocs/op
BenchmarkSIS/ring-sis/inputs=65536/log2-bound=32/log2-degree=8-10                     10         108187054 ns/op              1650 ns/field           1968 ns/field(theory)       204904 B/op       4112 allocs/op
```

TODO:

- [ ] generate test vectors from Sage

**Review by ThomasPiellard — APPROVED** [review]

**Pull request merged**
