### PR TITLE
Remove some useless code in fft.NewDomain

### PR DESCRIPTION
**Pull request by zhiqiangxu**
Just stumpled upon some useless code.

### CODE REVIEW

**Comment by ThomasPiellard** [comment]
Hi @zhiqiangxu , yes that's right thanks for spotting this. There is also `PrecomputeReversedTable` which is not used. Could you modify your PR to merge it to develop instead of master?

**Comment by ThomasPiellard** [comment]
Yes I will remove it, some comments need to be updated as well. Normally if I am not mistaken after the removal `PrecomputeReversedTable` only the marshal functions will be affected...

**Comment by zhiqiangxu** [comment]
> Yes I will remove it, some comments need to be updated as well. Normally if I am not mistaken after the removal of `PrecomputeReversedTable` only the marshal functions will be affected...

Right.

**Comment by zhiqiangxu** [comment]
> I didn't pay attention but in fact you didn't modify the templates for the code generation so there is some additional code to write. To save your commit, could you tweak the PR again to merge it to `feat/fft_cleanup` (I juste created this branch). I can add the other required modifications right now.

Done!

**Pull request merged**
