### PR TITLE
Perf: faster final exponentiation (hard part) for BW6 curves

### LINKED ISSUE #457: Optimize BW6 final exponentiation
Optimize the final exponentiation (FE) of BW6 curves following algorithms 4.3, 4.4, 4.5 and 4.6 of https://yelhousni.github.io/phd.pdf. The PR https://github.com/Consensys/gnark/pull/846 uses alg. 4.4 in-circuit, and for testing the hack now is to raise the result to 12. In fact, currently in gnark-crypto the FE power is 12(x₀+1)(p⁶-1)/r and in gnark (x₀+1)(p⁶-1)/r. Implementing these algorithms should speedup the different BW6 pairings in gnark-crypto too.

### PR DESCRIPTION
**Pull request by yelhousni**
# Description

This PR otpimizes the final exponentiation (hard part) of BW6 curves.
Fixes #457.

Todo:
- [x] BW6-761
- [x] BW6-756
- [x] BW6-633

The PR also removes some unnecessary computations in the Miller loop (some cases do not occur given the loopCounters).
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

Existing pairing tests still apply to the new version.

# How has this been benchmarked?

- [x] Benchmark A, on Macbook Air M1, 16GB RAM
- BW6-761
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-8     2592580       2343537       -9.61%
```
- BW6-756
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-8     2566568       2353209       -8.31%
```
- BW6-633
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-8     1574459       1463099       -7.07%
```
- [x] Benchmark B, on AWS z1d.large (Intel(R) Xeon(R) Platinum 8151 CPU @ 3.40GHz)
- BW6-761
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-2     2250893       2099406       -6.73%
```
- BW6-756
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-2     2453394       2321157       -5.39%
```
- BW6-633
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-2     1579874       1478325       -6.43%
```

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ivokub — APPROVED** [review]
LGTM

**Review by ivokub — APPROVED** [review]
LGTM

**Comment by yelhousni** [comment]
@ivokub I just added BW6-756 and BW6-633 new final exponentiations. For BW6-756 it's the same algorithm as the BW6-761 you reviewed (case t % r % x₀ = 3 in BW6-BLS12 family and algorithm 4.4 from [[PhD:Housni22]](https://yelhousni.github.io/phd.pdf)). It just happens that `Expc1` is a `Conjugate` and `Expc2` is the identity map. For BW6-633, it is different (case t % r % x₀ = 0 in BW6-BLS24 family and algorithm 4.5).

**Review by ivokub — APPROVED** [review]
Looks all good to me.

**Review by ivokub — APPROVED** [review]
Looks all good to me.

**Pull request merged**
